FROM openjdk:8

ADD SpringMicroserviceHelloWorldAdi2Application.jar /SpringMicroserviceHelloWorldAdi2Application.jar

EXPOSE 8090/tcp

ENTRYPOINT ["java", "-jar", "/SpringMicroserviceHelloWorldAdi2Application.jar"]
